import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Header from "@/components/Header"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className=" font-poppins duration-300 transition md:border-t-[4px] md:border-b-[4px] 2xl:border-r-[50px] 2xl:border-l-[50px] md:border-[30px]  border-t-[4px] border-b-[0px] border-white xl:border-r-[40px] xl:border-l-[40px]">
        <Header />
        <main>{children}</main>
        
      </body>
    </html>
  )
}
